"""Tests for the response-head control baselines.

These exist because the repository previously computed only a "predict no
change" baseline and quoted every external model from its paper. A learned head
that does not beat cheap retrieval over the same frozen embeddings has not been
shown to learn perturbation biology, so these controls need to be correct.
"""
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src" / "maprna_p3"))

from baselines import (  # noqa: E402
    REGISTRY, baseline_knn_esm2, baseline_neighbor_prior, baseline_ridge_esm2,
    baseline_train_mean, baseline_zero, run_all)


def _synthetic(n_tr=120, n_te=30, d=64, n_gene=50, seed=0):
    """Residuals generated by a known linear map from the embedding.

    Both a linear model and nearest-neighbour retrieval should recover signal
    here, which is what makes them meaningful controls.
    """
    rng = np.random.default_rng(seed)
    W = rng.normal(size=(d, n_gene))
    e_tr = rng.normal(size=(n_tr, d))
    e_te = rng.normal(size=(n_te, d))
    dev_tr = (e_tr @ W + 0.3 * rng.normal(size=(n_tr, n_gene))).astype(np.float32)
    dev_te = (e_te @ W + 0.3 * rng.normal(size=(n_te, n_gene))).astype(np.float32)
    return e_tr, e_te, dev_tr, dev_te


def _per_item_r(true, pred):
    rs = []
    for i in range(len(true)):
        if np.std(true[i]) > 1e-9 and np.std(pred[i]) > 1e-9:
            rs.append(np.corrcoef(true[i], pred[i])[0, 1])
    return float(np.mean(rs)) if rs else float("nan")


def test_shapes_and_dtypes():
    e_tr, e_te, dev_tr, _ = _synthetic()
    for name, pred in run_all(dev_tr, e_tr, e_te).items():
        assert pred.shape == (len(e_te), dev_tr.shape[1]), name
        assert np.isfinite(pred).all(), name


def test_zero_baseline_is_zero():
    e_tr, e_te, dev_tr, _ = _synthetic()
    assert not baseline_zero(dev_tr, e_tr, e_te).any()


def test_train_mean_ignores_the_query():
    """Every test perturbation must receive the same prediction."""
    e_tr, e_te, dev_tr, _ = _synthetic()
    p = baseline_train_mean(dev_tr, e_tr, e_te)
    assert np.allclose(p[0], p[-1])


def test_ridge_recovers_a_linear_signal():
    e_tr, e_te, dev_tr, dev_te = _synthetic()
    p = baseline_ridge_esm2(dev_tr, e_tr, e_te, alpha=1.0)
    assert _per_item_r(dev_te, p) > 0.7


def test_knn_recovers_signal_and_beats_train_mean():
    e_tr, e_te, dev_tr, dev_te = _synthetic()
    knn = _per_item_r(dev_te, baseline_knn_esm2(dev_tr, e_tr, e_te, k=10))
    mean = _per_item_r(dev_te, baseline_train_mean(dev_tr, e_tr, e_te))
    assert knn > 0.2
    assert knn > mean


def test_knn_excludes_identical_neighbours():
    """A test perturbation duplicated in training must not retrieve itself.

    This guards the interaction with the split defect (ERRATA E5): if the same
    target gene sits in both splits, self-retrieval turns the "baseline" into
    memorisation and it stops being a control.
    """
    e_tr, e_te, dev_tr, _ = _synthetic(n_te=5)
    # inject exact duplicates of the test embeddings into training, each
    # carrying a distinctive residual
    marker = np.full((len(e_te), dev_tr.shape[1]), 999.0, dtype=np.float32)
    e_tr2 = np.concatenate([e_tr, e_te])
    dev_tr2 = np.concatenate([dev_tr, marker])
    p = baseline_knn_esm2(dev_tr2, e_tr2, e_te, k=5)
    assert p.max() < 900, "self-retrieval was not excluded"


def test_knn_mask_restricts_averaging_to_measured_neighbours():
    """With a gene measured in only one neighbour, that neighbour's value wins."""
    rng = np.random.default_rng(1)
    n_tr, n_gene, d = 8, 4, 16
    e_tr = rng.normal(size=(n_tr, d))
    e_te = e_tr[:1] + 0.01 * rng.normal(size=(1, d))
    dev_tr = np.zeros((n_tr, n_gene), dtype=np.float32)
    mask = np.zeros((n_tr, n_gene), dtype=bool)
    dev_tr[3, 2] = 5.0
    mask[3, 2] = True                       # only row 3 measured gene 2
    p = baseline_knn_esm2(dev_tr, e_tr, e_te, mask_tr=mask, k=n_tr, weighted=False)
    assert abs(p[0, 2] - 5.0) < 1e-5
    assert p[0, 0] == 0.0                   # nothing measured gene 0


def test_ridge_handles_more_features_than_samples():
    """ESM2 is 5120-dimensional, so the dual path is the one usually taken."""
    e_tr, e_te, dev_tr, dev_te = _synthetic(n_tr=20, d=200, n_gene=10)
    p = baseline_ridge_esm2(dev_tr, e_tr, e_te, alpha=1.0)
    assert p.shape == (len(e_te), 10)
    assert np.isfinite(p).all()


# --------------------------------------------------------------------------
# neighbor_prior -- the fairness control for the model's network channel
# --------------------------------------------------------------------------

def test_neighbor_prior_degrades_to_train_mean_without_a_graph():
    """No graph supplied is a missing table, not an error."""
    rng = np.random.default_rng(0)
    dev_tr = rng.normal(size=(20, 30))
    esm_tr, esm_te = rng.normal(size=(20, 8)), rng.normal(size=(5, 8))
    got = baseline_neighbor_prior(dev_tr, esm_tr, esm_te)
    exp = baseline_train_mean(dev_tr, esm_tr, esm_te)
    assert np.allclose(got, exp, atol=1e-6)
    assert got.shape == (5, 30)


def test_neighbor_prior_recovers_a_planted_neighbour_effect():
    """If partners really deviate more, the one fitted parameter must find it."""
    rng = np.random.default_rng(1)
    n_tr, n_te, n_g = 60, 10, 40
    nb_tr = rng.random((n_tr, n_g)) < 0.2
    nb_te = rng.random((n_te, n_g)) < 0.2
    dev_tr = rng.normal(scale=0.05, size=(n_tr, n_g)) + 0.8 * nb_tr
    esm_tr, esm_te = rng.normal(size=(n_tr, 8)), rng.normal(size=(n_te, 8))
    pred = baseline_neighbor_prior(dev_tr, esm_tr, esm_te,
                                   is_nb_tr=nb_tr, is_nb_te=nb_te)
    # partner cells must be predicted clearly above non-partner cells
    assert pred[nb_te].mean() - pred[~nb_te].mean() > 0.5
    # and it must beat train_mean on a held-out set built the same way
    dev_te = rng.normal(scale=0.05, size=(n_te, n_g)) + 0.8 * nb_te
    tm = baseline_train_mean(dev_tr, esm_tr, esm_te)
    err_nb = float(np.mean((pred - dev_te) ** 2))
    err_tm = float(np.mean((tm - dev_te) ** 2))
    assert err_nb < err_tm, "the graph parameter did not help where it should"


def test_neighbor_prior_finds_nothing_when_the_graph_is_uninformative():
    """A control that 'helps' on a random graph would be leaking, not using it."""
    rng = np.random.default_rng(2)
    n_tr, n_te, n_g = 60, 10, 40
    dev_tr = rng.normal(size=(n_tr, n_g))
    nb_tr = rng.random((n_tr, n_g)) < 0.2          # unrelated to dev_tr
    nb_te = rng.random((n_te, n_g)) < 0.2
    esm_tr, esm_te = rng.normal(size=(n_tr, 8)), rng.normal(size=(n_te, 8))
    pred = baseline_neighbor_prior(dev_tr, esm_tr, esm_te,
                                   is_nb_tr=nb_tr, is_nb_te=nb_te)
    tm = baseline_train_mean(dev_tr, esm_tr, esm_te)
    # beta should be near zero, so the prediction stays close to train_mean
    assert np.abs(pred - tm).max() < 0.15


def test_neighbor_prior_respects_the_mask_when_fitting_beta():
    """Unmeasured cells must not contribute to the fitted graph parameter."""
    rng = np.random.default_rng(3)
    n_tr, n_g = 40, 20
    nb_tr = np.zeros((n_tr, n_g), bool); nb_tr[:, :5] = True
    dev_tr = rng.normal(scale=0.01, size=(n_tr, n_g))
    dev_tr[:, :5] += 5.0                            # huge effect, but masked out
    mask = np.ones((n_tr, n_g), bool); mask[:, :5] = False
    esm_tr, esm_te = rng.normal(size=(n_tr, 6)), rng.normal(size=(3, 6))
    pred = baseline_neighbor_prior(dev_tr, esm_tr, esm_te, mask_tr=mask,
                                   is_nb_tr=nb_tr, is_nb_te=np.ones((3, n_g), bool))
    assert np.isfinite(pred).all()
    # with every partner cell masked away, beta has no evidence and must stay ~0
    assert np.abs(pred).max() < 1.0, "masked cells leaked into the graph parameter"


def test_registry_exposes_the_graph_control():
    assert "neighbor_prior" in REGISTRY
    out = run_all(np.zeros((6, 10)), np.zeros((6, 4)), np.zeros((2, 4)),
                  which=["neighbor_prior"])
    assert out["neighbor_prior"].shape == (2, 10)
