"""Tests for the response-head control baselines.

These exist because the repository previously computed only a "predict no
change" baseline and quoted every external model from its paper. A learned head
that does not beat cheap retrieval over the same frozen embeddings has not been
shown to learn perturbation biology, so these controls need to be correct.
"""
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src" / "maprna_p3"))

from baselines import (  # noqa: E402
    baseline_knn_esm2, baseline_ridge_esm2, baseline_train_mean, baseline_zero, run_all)


def _synthetic(n_tr=120, n_te=30, d=64, n_gene=50, seed=0):
    """Residuals generated by a known linear map from the embedding.

    Both a linear model and nearest-neighbour retrieval should recover signal
    here, which is what makes them meaningful controls.
    """
    rng = np.random.default_rng(seed)
    W = rng.normal(size=(d, n_gene))
    e_tr = rng.normal(size=(n_tr, d))
    e_te = rng.normal(size=(n_te, d))
    dev_tr = (e_tr @ W + 0.3 * rng.normal(size=(n_tr, n_gene))).astype(np.float32)
    dev_te = (e_te @ W + 0.3 * rng.normal(size=(n_te, n_gene))).astype(np.float32)
    return e_tr, e_te, dev_tr, dev_te


def _per_item_r(true, pred):
    rs = []
    for i in range(len(true)):
        if np.std(true[i]) > 1e-9 and np.std(pred[i]) > 1e-9:
            rs.append(np.corrcoef(true[i], pred[i])[0, 1])
    return float(np.mean(rs)) if rs else float("nan")


def test_shapes_and_dtypes():
    e_tr, e_te, dev_tr, _ = _synthetic()
    for name, pred in run_all(dev_tr, e_tr, e_te).items():
        assert pred.shape == (len(e_te), dev_tr.shape[1]), name
        assert np.isfinite(pred).all(), name


def test_zero_baseline_is_zero():
    e_tr, e_te, dev_tr, _ = _synthetic()
    assert not baseline_zero(dev_tr, e_tr, e_te).any()


def test_train_mean_ignores_the_query():
    """Every test perturbation must receive the same prediction."""
    e_tr, e_te, dev_tr, _ = _synthetic()
    p = baseline_train_mean(dev_tr, e_tr, e_te)
    assert np.allclose(p[0], p[-1])


def test_ridge_recovers_a_linear_signal():
    e_tr, e_te, dev_tr, dev_te = _synthetic()
    p = baseline_ridge_esm2(dev_tr, e_tr, e_te, alpha=1.0)
    assert _per_item_r(dev_te, p) > 0.7


def test_knn_recovers_signal_and_beats_train_mean():
    e_tr, e_te, dev_tr, dev_te = _synthetic()
    knn = _per_item_r(dev_te, baseline_knn_esm2(dev_tr, e_tr, e_te, k=10))
    mean = _per_item_r(dev_te, baseline_train_mean(dev_tr, e_tr, e_te))
    assert knn > 0.2
    assert knn > mean


def test_knn_excludes_identical_neighbours():
    """A test perturbation duplicated in training must not retrieve itself.

    This guards the interaction with the split defect (ERRATA E5): if the same
    target gene sits in both splits, self-retrieval turns the "baseline" into
    memorisation and it stops being a control.
    """
    e_tr, e_te, dev_tr, _ = _synthetic(n_te=5)
    # inject exact duplicates of the test embeddings into training, each
    # carrying a distinctive residual
    marker = np.full((len(e_te), dev_tr.shape[1]), 999.0, dtype=np.float32)
    e_tr2 = np.concatenate([e_tr, e_te])
    dev_tr2 = np.concatenate([dev_tr, marker])
    p = baseline_knn_esm2(dev_tr2, e_tr2, e_te, k=5)
    assert p.max() < 900, "self-retrieval was not excluded"


def test_knn_mask_restricts_averaging_to_measured_neighbours():
    """With a gene measured in only one neighbour, that neighbour's value wins."""
    rng = np.random.default_rng(1)
    n_tr, n_gene, d = 8, 4, 16
    e_tr = rng.normal(size=(n_tr, d))
    e_te = e_tr[:1] + 0.01 * rng.normal(size=(1, d))
    dev_tr = np.zeros((n_tr, n_gene), dtype=np.float32)
    mask = np.zeros((n_tr, n_gene), dtype=bool)
    dev_tr[3, 2] = 5.0
    mask[3, 2] = True                       # only row 3 measured gene 2
    p = baseline_knn_esm2(dev_tr, e_tr, e_te, mask_tr=mask, k=n_tr, weighted=False)
    assert abs(p[0, 2] - 5.0) < 1e-5
    assert p[0, 0] == 0.0                   # nothing measured gene 0


def test_ridge_handles_more_features_than_samples():
    """ESM2 is 5120-dimensional, so the dual path is the one usually taken."""
    e_tr, e_te, dev_tr, dev_te = _synthetic(n_tr=20, d=200, n_gene=10)
    p = baseline_ridge_esm2(dev_tr, e_tr, e_te, alpha=1.0)
    assert p.shape == (len(e_te), 10)
    assert np.isfinite(p).all()
